const { Pool } = require('pg');

const pool = new Pool({
  host: process.env.DB_HOST,
  database: process.env.DB_NAME,
  user: process.env.DB_USER,
  password: process.env.DB_PASS || '',
});

const createTriggerFunctionQuery = `
  CREATE FUNCTION trigger_update_timestamp()
  RETURNS TRIGGER AS $$
  BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
  END;
  $$ LANGUAGE plpgsql;
`;

const setUsersTriggerFunctionQuery = `
  CREATE TRIGGER set_timestamp
  BEFORE UPDATE ON users
  FOR EACH ROW
  EXECUTE PROCEDURE trigger_update_timestamp();
`;

const setTokensTriggerFunctionQuery = `
  CREATE TRIGGER set_timestamp
  BEFORE UPDATE ON tokens
  FOR EACH ROW
  EXECUTE PROCEDURE trigger_update_timestamp();
`;

const setPostsTriggerFunctionQuery = `
  CREATE TRIGGER set_timestamp
  BEFORE UPDATE ON posts
  FOR EACH ROW
  EXECUTE PROCEDURE trigger_update_timestamp();
`;

const createUsersTableQuery = `
  CREATE TABLE users (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    username TEXT UNIQUE NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (id)
  );
`;

const createTokensTableQuery = `
  CREATE TABLE tokens (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    user_id INT UNIQUE NOT NULL,
    token TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
  );
`;

const createPostsTableQuery = `
  CREATE TABLE posts (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    user_id INT NOT NULL,
    content TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users (id)
  );
`;

const handleError = (err) => {
  switch (err.code) {
    case '42723':
      console.log('trigger_update_timestamp() already exists');
      break;
    case '42710':
      console.log('update trigger already set');
      break;
    case '42P07':
      // table exists
      console.log(err.message);
      break;
    default:
      console.log(err);
  }
}

const createTriggerFunction = () => {
  return new Promise((resolve, reject) => {
    pool.query(createTriggerFunctionQuery)
      .then(res => resolve('trigger_update_timestamp() created'))
      .catch(err => reject(err));
  });
}

const createUsersTable = () => {
  return new Promise((resolve, reject) => {
    pool.query(createUsersTableQuery)
      .then(res => resolve('users table created'))
      .catch(err => reject(err));
  });
}

const createTokensTable = () => {
  return new Promise((resolve, reject) => {
    pool.query(createTokensTableQuery)
      .then(res => resolve('tokens table created'))
      .catch(err => reject(err));
  });
}

const createPostsTable = () => {
  return new Promise((resolve, reject) => {
    pool.query(createPostsTableQuery)
      .then(res => resolve('posts table created'))
      .catch(err => reject(err));
  });
}

const usersTrigger = () => {
  return new Promise((resolve, reject) => {
    pool.query(setUsersTriggerFunctionQuery)
      .then(res => resolve('users update trigger set'))
      .catch(err => reject(err));
  });
}

const tokensTrigger = () => {
  return new Promise((resolve, reject) => {
    pool.query(setTokensTriggerFunctionQuery)
      .then(res => resolve('tokens update trigger set'))
      .catch(err => reject(err));
  });
}

const postsTrigger = () => {
  return new Promise((resolve, reject) => {
    pool.query(setPostsTriggerFunctionQuery)
      .then(res => resolve('posts update trigger set'))
      .catch(err => reject(err));
  });
}

// THIS MOSTLY WORKS
// returns annoying objects when there are dupes
createTriggerFunction()
  .catch(err => handleError(err))
  .then(createUsersTable)
  .then(res => console.log(res))
  .catch(err => handleError(err))
  .then(() => {
    return Promise.allSettled([createTokensTable(), createPostsTable()])
      .then(res => res.forEach(r => console.log(r)))
  })
  .then(() => {
    return Promise.allSettled([usersTrigger(), tokensTrigger(), postsTrigger()])
      .then(res => res.forEach(r => console.log(r)))
  })
  .catch(err => handleError(err));

module.exports = {
  query: (text, params, callback) => {
    return pool.query(text, params, callback);
  },
};
